--QUERY 1
SELECT 
	TR.ID_TRANSACTION, 
	CO.TRADENAME, 
	TO_CHAR(TR.TRANSACTION_VALUE,'FM000,000,000.00'),
	TO_CHAR(TR.TRANSACTION_TOTAL,'FM000,000,000.00'),
	TO_CHAR( START_DATE_FULL, 'FMDy, DD Mon YYYY - HH24:MI' )
FROM 
	CORE_TRANSACTION TR 
INNER JOIN 
	CORE_CONTACT CO ON (TR.ID_CONTACT = CO.ID_CONTACT AND TR.NICKNAME_OWNER_CONTACT = CO.NICKNAME_OWNER)
INNER JOIN 
	CORE_TRANSACTIONTYPE TP ON (TP.ID_TRANSACTION_TYPE = TR.ID_TRANSACTION_TYPE AND TP.NICKNAME_OWNER = TR.NICKNAME_OWNER_TYPE)
WHERE
	UPPER(TP.TRANSACTION_TYPE_NAME) = 'VENTA' AND 
	TR.START_DATE_FULL >= TO_DATE('2022/01/01', 'yyyy/mm/dd')
ORDER BY 
	CO.TRADENAME DESC, 
	TR.START_DATE_FULL DESC 

--QUERY 2
SELECT 
	CO.TRADENAME,
	COUNT(*),
	TO_CHAR(SUM(TR.TRANSACTION_TOTAL),'FM000,000,000.00')
FROM 
	CORE_TRANSACTION TR 
INNER JOIN 
	CORE_CONTACT CO ON (TR.ID_CONTACT = CO.ID_CONTACT AND TR.NICKNAME_OWNER_CONTACT = CO.NICKNAME_OWNER)
INNER JOIN
	CORE_TRANSACTIONTYPE TP ON (TP.ID_TRANSACTION_TYPE = TR.ID_TRANSACTION_TYPE AND TP.NICKNAME_OWNER = TR.NICKNAME_OWNER_TYPE)
WHERE
	UPPER(TP.TRANSACTION_TYPE_NAME) = 'VENTA'
GROUP BY
	CO.TRADENAME

--QUERY 3
SELECT 
	PR.PRODUCT_NAME,
	SUM(TD.QUANTITY) AS "CANTIDAD",
	TO_CHAR(SUM(TD.TRANSACTIONDETAIL_DISCOUNT),'FM000,000,000.00') AS "MONTO_TOTAL_DESCUENTO",
	TO_CHAR(SUM(TD.TRANSACTIONDETAIL_TAX),'FM000,000,000.00') AS "MONTO_TOTAL_IMPUESTO",
	TO_CHAR(SUM(TD.PRICE * TD.QUANTITY),'FM000,000,000.00') AS "MONTO_SUBTOTAL",
	TO_CHAR(SUM(TD.PRICE * TD.QUANTITY) - SUM(TD.TRANSACTIONDETAIL_DISCOUNT) + SUM(TD.TRANSACTIONDETAIL_TAX),'FM000,000,000.00') AS "MONTO_TOTAL"
FROM
	CORE_PRODUCT PR
INNER JOIN
	CORE_TRANSACTIONDETAIL TD ON (TD.ID_PRODUCT = PR.ID_PRODUCT AND TD.NICKNAME_OWNER_PRODUCT = PR.NICKNAME_OWNER)
WHERE
	UPPER(PR.NICKNAME_OWNER) = 'DISNOVO'
GROUP BY
	PR.PRODUCT_NAME
ORDER BY
	SUM(TD.PRICE * TD.QUANTITY) - SUM(TD.TRANSACTIONDETAIL_DISCOUNT) + SUM(TD.TRANSACTIONDETAIL_TAX) DESC,
	PR.PRODUCT_NAME


--QUERY 4
SELECT 
    PR.PRODUCT_NAME, 
	TO_CHAR(PR.PRICE*1.15,'FM000,000,000.00') AS "PRICE_ADD_15_PERCENTAGE"
FROM
	CORE_PRODUCT PR
INNER JOIN
	CORE_PRODUCTTYPE TP ON (TP.ID_PRODUCT_TYPE = PR.ID_PRODUCT_TYPE AND TP.NICKNAME_OWNER = PR.NICKNAME_OWNER_TYPE)
WHERE
	UPPER(TP.PRODUCT_TYPE_NAME) = 'CARNE'


--QUERY 5
DELETE FROM
	CORE_TRANSACTION TR
WHERE EXISTS(
	SELECT 
		* 
	FROM 
		CORE_CONTACT CO
	WHERE 
		TR.ID_CONTACT = CO.ID_CONTACT AND 
		TR.NICKNAME_OWNER_CONTACT = CO.NICKNAME_OWNER AND
		UPPER(CO.TRADENAME) = 'JUAN PÉREZ'
)

 --QUERY 6  
SELECT 
	JSON_ARRAYAGG(
		JSON_OBJECT(
			'nombre' : PR.PRODUCT_NAME,
			'cantidad' : SUM(TD.QUANTITY),
			'subtotal' : TO_CHAR(SUM(TD.TRANSACTIONDETAIL_DISCOUNT),'FM000,000,000.00'),
			'total_descuento' : TO_CHAR(SUM(TD.TRANSACTIONDETAIL_TAX),'FM000,000,000.00'),
			'total_impuesto' : TO_CHAR(SUM(TD.PRICE * TD.QUANTITY),'FM000,000,000.00'),
			'total' : TO_CHAR(SUM(TD.PRICE * TD.QUANTITY) - SUM(TD.TRANSACTIONDETAIL_DISCOUNT) + SUM(TD.TRANSACTIONDETAIL_TAX),'FM000,000,000.00')
			)
            ORDER BY 
                SUM(TD.PRICE * TD.QUANTITY) - SUM(TD.TRANSACTIONDETAIL_DISCOUNT) + SUM(TD.TRANSACTIONDETAIL_TAX) DESC,
				PR.PRODUCT_NAME
		)
FROM 
	CORE_PRODUCT PR
INNER JOIN 
	CORE_TRANSACTIONDETAIL TD ON (TD.ID_PRODUCT = PR.ID_PRODUCT AND TD.NICKNAME_OWNER_PRODUCT = PR.NICKNAME_OWNER)
WHERE 
	PR.NICKNAME_OWNER = 'DISNOVO'
GROUP BY 
	PR.PRODUCT_NAME

